My commit
Lotholl/hardhardlemonhard pull request #4
Opened 2020-10-17 18:58 UTC by MorgothSD

2020-10-17 20:29 UTC, Lotholl requested changes
Большой вопрос по классам

2020-10-17 20:29 UTC, Lotholl commented on 7/New Unity Project/Assets/BricksT.cs
> +public class BricksT : DecSize
Хотелось бы услышать комментарий, почему всё таким необычным образом наследуется, что тут, что тем более где BrickT & EgyptT наследуют один другого, и уж особенно, почему Save и Load потом наследуются от них

2020-10-17 20:29 UTC, Lotholl commented on 7/New Unity Project/Assets/Save.cs
> +        else if (meshRenderer.material.GetTexture("_MainTex") == Egypt) sw.WriteLine("Egypt texture"); // записываем в файл строку
Лучше было бы писать в какой-нибудь json, а не просто текстом

2020-10-17 22:22 UTC, MorgothSD commented on 7/New Unity Project/Assets/BricksT.cs
> +public class BricksT : DecSize
Изначально у меня были большие проблемы с сохранением. Мною был выбран вариант добавить переменные isBrick и isEgypt типов boolean в класс isBrickT, дабы отслеживать изменение текстуры, соответственно были прикручены сеттеры SetIsBrickTrue и SetIsEgyptTrue, для установки их в соответствующие значения при нажатии на кнопку, но при записи в файл у меня никак не получалось проверить текущую текстуру через эти bool переменные, потому что какого-то хрена isBrick всегда оказывалась false, когда как isEgypt работала нормально, затем я отказался от этих переменных. Следующим решением я сделал переменную string check, куда записывал имя текущей текстуры для проверки при записи, но это тоже не дало результата, потому что у меня не получалось сохранять несколько раз. В конце концов я, почитав документацию по Unity, сделал адекватную проверку на текущую текстуру, так что по факту наследование осталось исключительно для переноса таких переменных как meshRenderer, имен текстур Bricks и Egypt и переменной scale (для изменения масштаба из любого класса наследника).

2020-10-17 22:31 UTC, MorgothSD commented on 7/New Unity Project/Assets/Save.cs
> +        else if (meshRenderer.material.GetTexture("_MainTex") == Egypt) sw.WriteLine("Egypt texture"); // записываем в файл строку
Я решил, что сейчас проще просто текстовый, учитывая что у меня всего одна фигура и сохраняются всего 2 параметра, с json работал только в js и то пару раз)

2020-10-18 00:36 UTC, Lotholl commented on 7/New Unity Project/Assets/BricksT.cs
> +public class BricksT : DecSize
Меня не сколько часть с Egypt/Brick смущает, сколько отдельные классы под методы Increase и Decrease, ну и реализация методов Save и Load мало того, что снова по отдельности, так ещё и в классе, наследуемом от EgyptT/BrickT. В итоге цепочка IncSize<- DecSize <- BrickT <- EgyptT <-Save<-Load выглядит ну очень неестественно. Почему общие методы просто не вынесены в один родительский класс, например?

2020-10-18 09:31 UTC, MorgothSD commented on 7/New Unity Project/Assets/BricksT.cs
> +public class BricksT : DecSize
Когда у меня методы были в одном классе, то я почему-то не мог привязать их на кнопку (когда я нажимал +, выбирал объект куб, а затем метод, то для выбора был почему-то доступен только самый верхний метод, который я добавил в класс, а остальные просто не отображались в контекстном меню), потом я пофиксил это, когда делал методы SetIsBrickTrue и SetIsEgyptTrue и оставил как есть. Могу объединить, если надо)

2020-10-19 09:48 UTC, merged